---
galaxy_info:
  author: skai-shiroe
  description: Nginx en équilibreur de charge devant les instances web
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - nginx
    - loadbalancer
    - reverseproxy
dependencies: []

