---
galaxy_info:
  author: skai-shiroe
  description: Déploie l'application Laravel (git, .env, composer, permissions)
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - laravel
    - php
    - webapp
dependencies: []

